# Generated by Django 4.2.7 on 2023-11-16 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_tracking_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(default='Test 1', max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('text_body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('not_delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
